# Generated by Django 5.2 on 2025-10-07 21:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="erd_image",
            new_name="image",
        ),
    ]
