# Generated by Django 5.2 on 2025-10-06 00:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="file",
            field=models.FileField(blank=True, upload_to="readmes/"),
        ),
    ]
