# Generated by Django 5.2 on 2025-10-06 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_rename_user_project_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='erd_url',
        ),
        migrations.AddField(
            model_name='project',
            name='erd_image',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
