# Generated by Django 5.2 on 2025-10-09 00:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_user_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='views',
        ),
        migrations.AddField(
            model_name='project',
            name='viewers',
            field=models.ManyToManyField(blank=True, editable=False, related_name='viewed_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
