# Generated by Django 5.2 on 2025-10-09 00:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0005_alter_project_viewers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="viewers",
            field=models.ManyToManyField(
                blank=True,
                editable=False,
                related_name="viewed_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
