
services:
    db:
        image: postgres
        ports:
          - "5432:5432"
        env_file:
            - .env.prod
        networks:
            - web-network

    web:
        build: .
        volumes:
            - .:/usr/src/app
            - staticfiles:/usr/src/app/staticfiles
            - media:/usr/src/app/media
        environment:
            - PRODUCTION=true
        env_file:
            - .env.prod
        networks:
            - web-network
        depends_on:
            - db

    nginx:
        build: ./nginx
        volumes:
            - staticfiles:/usr/src/app/staticfiles
            - media:/usr/src/app/media  
        ports:
            - "8080:80"
        networks:
            - web-network
        depends_on:
            - web

volumes:
    staticfiles:
    media:

networks:
    web-network:
        driver: bridge
